openapi: 3.0.3
info:
  title: Onboarding Api
  description: STD 22030
  version: 1.0.1
servers:
  - url: https://STD22030/api
paths:
  /Students:
    post:
      tags:
        - Students
      summary: Add a new student
      description: Add a new student
      operationId: AddStudent
      requestBody:
        description: Add a new student on the list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Students'
        required: true
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal Server Error
      security:
        - Students_auth:
            - write:Student
            - read:Student
    get:
      tags:
        - Students
      summary: Find student by ID
      description: Returns a single student
      operationId: getStudentById
      parameters:
        - name: StudentsID
          in: path
          description: ID of Student to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
        - Students_auth:
            - write:Student
            - read:Student
    put:
      tags:
        - Students
      summary: Update Students information by ID
      description: Update a single student
      operationId: getStudentById
      parameters:
        - name: StudentsID
          in: path
          description: ID of Student to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
        - Students_auth:
            - write:Student
            - read:Student
    delete:
      tags:
        - Students
      summary: Delete a student
      description: Delete information about a student
      operationId: Delete a student by ID
      parameters:
        - name: StudentsID
          in: path
          description: ID of Student to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
        - Students_auth:
          - write:Student
          - read:Student
  /Teachers:
    post:
      tags:
        - Teachers
      summary: Add a new teacher
      description: Add a new teacher
      operationId: AddTeacher
      requestBody:
        description: Add a new teachers on the list
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teachers'
        required: true
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal Server Error
      security:
        - Teachers_auth:
            - write:Teacher
            - read:Teacher
    get:
      tags:
        - Teachers
      summary: Find teacher by ID
      description: Returns a single Teacher
      operationId: getTeachersById
      parameters:
        - name: TeachersID
          in: path
          description: ID of Teacher to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '500':
          description: Internal Server Error
      security:
        - api_key: [ ]
        - Teachers_auth:
            - write:Teacher
            - read:Teacher
components:
  schemas:
    Students:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Andrew Hopkins
        birthdate:
          type: string
          example: 2000-01-03
        STD :
          type: string
          example: STD22030

    Teachers:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        lastName:
          type: string
          example: Rakotondratompo
        firstName:
          type: string
          example: Bako Harry
        courses:

          type: array
          items:
            type: object
            properties:
              courseName:
                type: string
                example: Systèmes et réseaux
              courseDuration:
                type: string
                example: 50h
              courseCode:
                type: string
                example: Sys1
